version: 2.1
parameters:
  GHA_Event:
    type: string
    default: ""
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

executors:
  hs_checkmarx:
    docker:
      - image: .../headspace/hs-checkmarx:latest
jobs:
  checkmarx:
    executor: hs_checkmarx
    parameters: # parameters that will be overriden for each repo
      #repo_name:
      #  type: string
      #repo_url:
      #  type: string
      #  default: $CIRCLE_REPOSITORY_URL
      branch:
        type: string
        default: master
      #cx_project:
      #  type: string
    steps:
      - run:
        command: cx_cli scan-with-report
          --cx-user=alan.nguyen@checkmarx.com
          --cx-pass=$CHECKMARX_PASS
          --cx-secret=$CHECKMARX_CLIENT_SECRET
          --jira-user=$CHECKMARX_JIRA_USER
          --jira-token=$CHECKMARX_JIRA_TOKEN
          --github-token=$CHECKMARX_GITHUB_TOKEN
          --cx-project="dummy"
          #--repo-name="dummy"
          #--repo-url=<<parameters.repo_url>>
         #--branch=<<parameters.branch>>
workflows:
  release:
    when:
      equal: [ "push", << pipeline.parameters.GHA_Event >>]
    jobs:
      - checkmarx
