name: Checkmarx SAST Scan-CLI
on:
  push:
    branches:
      - master
      - main
      - 'feature/**'
jobs:
  Checkmarx-cli-scan:
    name: Run Checkmarx CLI Scan
    runs-on: self-hosted
    steps:
    - name: Download CxCLI Zip
      run: wget -O ~/cxcli.zip https://download.checkmarx.com/8.9.0/Plugins/CxConsolePlugin-8.90.0.zip
    - name: Unzip CxCLI Zip
      run: unzip -o ~/cxcli.zip -d ~/cxcli
    - name: Make CxCLI executable
      run: chmod +x ~/cxcli/runCxConsole.sh
    - uses: actions/checkout@v2
    - name: Run Checkmarx Scan
      env:
        CX_SERVER: ${{ secrets.CHECKMARX_URL }}
        CX_TEAM: CxServer
        CX_PRESET: Checkmarx Default
        CX_USER: ${{ secrets.CHECKMARX_USER }}
        CX_PASSWORD: ${{ secrets.CHECKMARX_PASSWORD }}
        CX_HIGH: 100
        CX_MEDIUM: 500
        CX_LOW: 1000
      run: |
        export CX_PROJECT_NAME=cxflow-gitrunners
        ~/cxcli/runCxConsole.sh Scan -CxServer $CX_SERVER -CxUser $CX_USER -CxPassword $CX_PASSWORD -ProjectName "$CX_TEAM\\$CX_PROJECT_NAME" -preset "$CX_PRESET" -LocationType folder -LocationPath $GITHUB_WORKSPACE -SASTHigh $CX_HIGH -SASTMedium $CX_MEDIUM -SASTLow $CX_LOW -ReportXML $GITHUB_WORKSPACE/results.xml -ReportPDF $GITHUB_WORKSPACE/results.pdf -verbose
    - name: Upload PDF Artifact
      uses: actions/upload-artifact@master
      with:
        name: results.pdf
        path: results.pdf
    - name: Upload XML Artifact
      uses: actions/upload-artifact@master
      with:
        name: results.xml
        path: results.xm
