name: Checkmarx SAST Scan-CLI
on:
  push:
    branches:
      - master1
jobs:
  Checkmarx-cxflow-cli-scan:
    name: Run Checkmarx CLI Scan
    runs-on: ubuntu-latest
    steps:
    - name: Download CxOne CLI
      run: |
        wget -q https://github.com/Checkmarx/ast-cli/releases/download/2.0.42/ast-cli_2.0.42_linux_x64.tar.gz -O cli.tar.gz
        tar -xzvf cli.tar.gz
        rm -rf cli.tar.gz
    - name: Run CxFlow CxSAST Scan
      env:
        CX_SERVER: ${{ secrets.CHECKMARX_URL }}
        CX_TEAM: CxServer
        CX_PRESET: Checkmarx Default
        CX_USER: ${{ secrets.CHECKMARX_USER }}
        CX_PASSWORD: ${{ secrets.CHECKMARX_PASSWORD }}
      run: |
        export CX_PROJECT_NAME=${{ github.event.repository.name }}
        ./cx

