name: Checkmarx SAST Scan-CLI
on:
  push:
    branches:
      - master1
jobs:
  Checkmarx-cxflow-cli-scan:
    name: Run Checkmarx CLI Scan
    runs-on: ubuntu-latest
    steps:
    - name: Download CxOne CLI
      run: |
        wget -q https://github.com/Checkmarx/ast-cli/releases/download/2.0.42/ast-cli_2.0.42_linux_x64.tar.gz -O cli.tar.gz
        tar -xzvf cli.tar.gz
        rm -rf cli.tar.gz
    - name: Run CxFlow CxSAST Scan
      run: |
        export CX_PROJECT_NAME=${{ github.event.repository.name }}
        ./cx --base-uri https://ast.checkmarx.net --tenant prod_na_testing --scan create --project-name NodeGoatAlan --file-source https://github.com/my-org/my-repo --branch main

