name: Checkmarx SAST Scan-CLI
on:
  push:
    branches:
      - notrealbranch2
jobs:
  Checkmarx-cxflow-cli-scan:
    name: Run Checkmarx CLI Scan
    runs-on: [ubuntu-latest]
    steps:
    - name: Download CxFlow jar
      run: wget -O ~/cxflow.jar https://github.com/checkmarx-ltd/cx-flow/releases/download/1.6.46/cx-flow-1.6.46.jar
    - name: Make CxFlow executable
      run: chmod +x ~/cxflow.jar
    - uses: actions/checkout@v1
    - name: Run CxFlow CxSAST Scan
      env:
        CX_SERVER: ${{ secrets.CHECKMARX_URL }}
        CX_PRESET: Checkmarx Default
        CX_USER: ${{ secrets.CHECKMARX_USER }}
        CX_PASSWORD: ${{ secrets.CHECKMARX_PASSWORD }}
      run: |
        export CX_PROJECT_NAME=${{ github.event.repository.name }}
        sudo java -Xmx6g -jar ~/cxflow.jar --scan --f=. --preset=Checkmarx Default --repo-name=${{ github.event.repository.name }} --cx-project=NodeGoat --branch=${{ github.ref_name }} --app=NodeGoat --checkmarx.base-url=https://cxprivatecloud.checkmarx.net --checkmarx.team="CxServer/SP/America/PSNA/AlanNguyen" --cxflow.bug-tracker="NONE" --checkmarx.username=alan.nguyen@checkmarx.com --checkmarx.password=Mk18mod0.. --app=NodeGoat --branch=master --cx-project=NodeGoat --checkmarx.multitenant=true --checkmarx.version=9.6 --comment="new cmm"
