name: Kics Scan
on:
  push:
    branches:
      - master1
jobs:
  Checkmarx-kics-scan:
    name: Run Checkmarx KICS Scan
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    - name: run kics Scan
      uses: checkmarx/kics-github-action@v1.6.3
      with:
        path: 'Dockerfile'
        output_path: myResults/
    - name: display kics results
      run: |
        cat myResults/results.json
